SELECT CART_ID
FROM (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE LOWER(NAME) IN ('yogurt', 'milk')
    GROUP BY CART_ID, NAME
)
GROUP BY CART_ID
HAVING COUNT(CART_ID) = 2
ORDER BY CART_ID