-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    INFO.GENDER,
    COUNT(DISTINCT INFO.USER_ID) AS USERS
FROM USER_INFO AS INFO JOIN ONLINE_SALE AS SALE
ON INFO.USER_ID = SALE.USER_ID
WHERE INFO.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER