


SELECT
    EXTRACT(YEAR FROM SALE.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALE.SALES_DATE) AS MONTH,
    USERS.GENDER AS GENDER,
    COUNT(DISTINCT USERS.USER_ID) AS USERS
FROM
    USER_INFO USERS JOIN ONLINE_SALE SALE
    ON USERS.USER_ID = SALE.USER_ID
WHERE USERS.GENDER IS NOT NULL
GROUP BY
    EXTRACT(YEAR  FROM SALE.SALES_DATE),
    EXTRACT(MONTH FROM SALE.SALES_DATE),
    USERS.GENDER
ORDER BY YEAR, MONTH, GENDER 