WITH TEMP_SALES AS (
    SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
)

SELECT *
FROM TEMP_SALES
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-03"
ORDER BY 1, 2, 3
