# SELECT
#     DATE_FORMAT(SALE.SALES_DATE, "%Y") AS YEAR,
#     DATE_FORMAT(SALE.SALES_DATE, "%c") AS MONTH,
#     COUNT(ONLINE_SALE_ID) AS PUCHASED_USERS,
#     ROUND(
#         COUNT(ONLINE_SALE_ID) / (
#             SELECT COUNT(*)
#             FROM USER_INFO
#             WHERE DATE_FORMAT(JOINED, "%Y") = "2021"
#         ), 1
#     ) AS PUCHASED_RATIO
# FROM USER_INFO AS USER JOIN ONLINE_SALE AS SALE
# ON USER.USER_ID = SALE.USER_ID
# WHERE DATE_FORMAT(USER.JOINED, "%Y") = "2021"
# GROUP BY YEAR, MONTH
# ORDER BY 1, 2

WITH TEMP_JOINED_USERS AS (
    SELECT *
    FROM USER_INFO
    WHERE DATE_FORMAT(JOINED, "%Y") = "2021"
)

SELECT 
    DATE_FORMAT(SALE.SALES_DATE, "%Y") AS YEAR,
    DATE_FORMAT(SALE.SALES_DATE, "%m") AS MONTH,
    COUNT(DISTINCT(USERS.USER_ID)) AS PUCHASED_USERS,
    ROUND(
        COUNT(DISTINCT(USERS.USER_ID)) /
        (SELECT COUNT(*) FROM TEMP_JOINED_USERS)
    , 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS SALE JOIN TEMP_JOINED_USERS AS USERS
ON SALE.USER_ID = USERS.USER_ID
GROUP BY YEAR, MONTH
ORDER BY 1, 2