-- 코드를 입력하세요
SELECT
    USER.USER_ID,
    USER.NICKNAME,
    CONCAT(USER.CITY, " ", USER.STREET_ADDRESS1, " ", USER.STREET_ADDRESS2) AS "전체주소", 
    CONCAT(
        SUBSTRING(USER.TLNO, 1, 3),
        "-",
        SUBSTRING(USER.TLNO, 4, 4),
        "-",
        SUBSTRING(USER.TLNO, 8, 4)
    )AS "전화번호"
FROM USED_GOODS_USER AS USER RIGHT JOIN USED_GOODS_BOARD AS BOARD
ON USER.USER_ID = BOARD.WRITER_ID
GROUP BY USER.USER_ID
HAVING COUNT(USER.USER_ID) >= 3
ORDER BY USER.USER_ID DESC