-- 코드를 입력하세요
WITH TEMP_CATEGORY_PRODUCT_MAX_PRICE AS (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE
    CATEGORY IN ("과자", "국", "김치", "식용유") AND
    PRICE IN (SELECT * FROM TEMP_CATEGORY_PRODUCT_MAX_PRICE)
ORDER BY PRICE DESC
