-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(SALES.SALES) AS TOTAL_SALES
FROM BOOK JOIN BOOK_SALES AS SALES
ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE DATE_FORMAT(SALES.SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY