SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A
    LEFT JOIN (
        SELECT HOST_ID, CASE WHEN COUNT(*) >= 2 THEN 1 ELSE 0 END AS IS_HEAVY_USER
        FROM PLACES
        GROUP BY HOST_ID
    ) B ON A.HOST_ID = B.HOST_ID
WHERE IS_HEAVY_USER = 1