SELECT
    AUTHOR.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    SUM(BOOK.PRICE * SALES.SALES) AS TOTAL_SALES
FROM 
    BOOK
    JOIN BOOK_SALES AS SALES
    ON BOOK.BOOK_ID = SALES.BOOK_ID
    JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC