WITH TEMP_RENTAL_TRUCK_HISTORY AS (
    SELECT
        CAR.CAR_ID,
        CAR.CAR_TYPE,
        CAR.DAILY_FEE,
        HIS.HISTORY_ID,
        DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 AS DATEDIFF,
        (CASE
            WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 7 AND DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 < 30
                THEN "7일 이상"
            WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 30 AND DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 < 90
                THEN "30일 이상"
            WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 90
                THEN "90일 이상"
            ELSE NULL
        END) AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_CAR AS CAR
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
        ON CAR.CAR_ID = HIS.CAR_ID
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
        ON CAR.CAR_TYPE = PLAN.CAR_TYPE
    WHERE
        CAR.CAR_TYPE = "트럭"
    GROUP BY
        HIS.HISTORY_ID
    ORDER BY CAR.CAR_ID
)

SELECT
    HIS.HISTORY_ID,
    ROUND(HIS.DAILY_FEE * (1 - IFNULL(PLAN.DISCOUNT_RATE, 0) / 100) * HIS.DATEDIFF, 0) AS FEE
FROM
    TEMP_RENTAL_TRUCK_HISTORY AS HIS
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
    ON HIS.CAR_TYPE = PLAN.CAR_TYPE AND HIS.DURATION_TYPE = PLAN.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC