-- 코드를 입력하세요

SELECT
    *,
    DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1
    # CAR.DAILY_FEE * (1 - PALN.DISCOUNT_RATE / 100)) * (DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1),
FROM 
    CAR_RENTAL_COMPANY_CAR AS CAR
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
    ON CAR.CAR_ID = HIS.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
    ON
        CAR.CAR_TYPE = PLAN.CAR_TYPE
        
WHERE CAR.CAR_TYPE = "트럭"
ORDER BY CAR.CAR_ID