-- 코드를 입력하세요
SELECT APP.APNT_NO, PAT.PT_NAME, PAT.PT_NO, APP.MCDP_CD, DOC.DR_NAME, APP.APNT_YMD
FROM
    APPOINTMENT AS APP
    JOIN PATIENT AS PAT
    ON APP.PT_NO = PAT.PT_NO
    JOIN DOCTOR AS DOC
    ON APP.MDDR_ID = DOC.DR_ID
WHERE
    DATE_FORMAT(APP.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND
    APP.APNT_CNCL_YN = "N" AND
    APP.MCDP_CD = "CS"
ORDER BY APP.APNT_YMD