-- 코드를 입력하세요
SELECT RENTAL.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS RENTAL LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
ON RENTAL.CAR_ID = HISTORY.CAR_ID
WHERE 
    RENTAL.CAR_TYPE = "세단" AND 
    DATE_FORMAT(HISTORY.START_DATE, "%Y-%m") >= "2022-10"
GROUP BY RENTAL.CAR_ID
ORDER BY RENTAL.CAR_ID DESC